// Products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_MORE_PRODUCTS = 'RECEIVE_MORE_PRODUCTS';
export const OPEN_PRODUCT = 'OPEN_PRODUCT';
export const WAIT_PRODUCTS_RESPONSE = 'WAIT_PRODUCTS_RESPONSE';
export const RECEIVE_PRODUCTS_RESPONSE = 'RECEIVE_PRODUCTS_RESPONSE';
export const ENABLE_HAS_MORE_PRODUCTS = 'ENABLE_HAS_MORE_PRODUCTS';
export const DISABLE_HAS_MORE_PRODUCTS = 'DISABLE_HAS_MORE_PRODUCTS';
export const ENABLE_INFINITY_PRODUCTS = 'ENABLE_INFINITY_PRODUCTS';
export const SET_COLUMN_NUMBER = 'SET_COLUMN_NUMBER';

// Auth
export const RECEIVED_AUTH_DATA = 'RECEIVED_AUTH_DATA';

// User
export const RECEIVE_USER = 'RECEIVE_USER';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

// Search
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';
export const SELECT_TAG = 'SELECT_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

// Popups
export const SHOW_POPUP_SIGNUP = 'SHOW_POPUP_SIGNUP';
export const HIDE_POPUP_SIGNUP = 'HIDE_POPUP_SIGNUP';
export const SHOW_POPUP_FAST_SIGNUP = 'SHOW_POPUP_FAST_SIGNUP';
export const HIDE_POPUP_FAST_SIGNUP = 'HIDE_POPUP_FAST_SIGNUP';

//Conversation
export const CONVERSATION_SET = 'CONVERSATION_SET';
export const CONVERSATION_RECEIVE_MESSAGE = 'CONVERSATION_RECEIVE_MESSAGE';
export const CONVERSATION_LOAD_MESSAGE = 'CONVERSATION_LOAD_MESSAGE';
export const CONVERSATION_SET_SHOW_MENU = 'CONVERSATION_SET_SHOW_MENU';
export const CONVERSATION_SET_SHOW_STATUS_MENU = 'CONVERSATION_SET_SHOW_STATUS_MENU';
export const CONVERSATION_SET_STATUS = 'CONVERSATION_SET_STATUS';
export const CONVERSATION_AFTER_LOAD_IMG = 'CONVERSATION_AFTER_LOAD_IMG';
export const CONVERSATION_SET_LAST_MESSAGE = 'CONVERSATION_SET_LAST_MESSAGE';
export const CONVERSATION_CLOSE = 'CONVERSATION_CLOSE';

//Lead
export const LEAD_INIT = 'LEAD_INIT';
export const LEAD_RECEIVE = 'LEAD_RECEIVE';
export const LEAD_SET_TAB = 'LEAD_SET_TAB';
export const LEAD_INC_NOTIFY = 'LEAD_INC_NOTIFY';
export const LEAD_CLEAR_NOTIFY = 'LEAD_CLEAR_NOTIFY';
export const LEAD_INC_LENGTH_LIST = 'LEAD_INC_LENGTH_LIST';
export const LEAD_UPDATE = 'LEAD_UPDATE';
export const LEAD_CLOSE = 'LEAD_CLOSE';

