// Products
export const PRODUCTS_FORCE_RECEIVE = 'PRODUCTS_FORCE_RECEIVE';
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE';
export const PRODUCTS_SET_OPENED_PRODUCT = 'PRODUCTS_SET_OPENED_PRODUCT';
export const PRODUCTS_SET_LIST_ID = 'PRODUCTS_SET_LIST_ID';
export const PRODUCTS_UPDATE_LIKED_BY = 'PRODUCTS_UPDATE_LIKED_BY';
export const PRODUCTS_INC_LENGTH_LIST = 'PRODUCTS_INC_LENGTH_LIST';
export const PRODUCTS_SET_COLUMN_NUMBER = 'PRODUCTS_SET_COLUMN_NUMBER';
export const PRODUCTS_LOADING= 'PRODUCTS_LOADING';
export const PRODUCTS_SET_INFINITY = 'PRODUCTS_SET_INFINITY';
export const PRODUCTS_SET_SCROLL = 'PRODUCTS_SET_SCROLL';
export const PRODUCTS_SET_ANIMATE = 'PRODUCTS_SET_ANIMATE';
export const PRODUCTS_CLOSE = 'PRODUCTS_CLOSE';
export const PRODUCTS_SET_CALL_BACK_AFTER_LOADING = 'PRODUCTS_SET_CALL_BACK_AFTER_LOADING';
export const PRODUCTS_SET_COME_BACK = 'PRODUCTS_SET_COME_BACK';

// Auth
export const RECEIVED_AUTH_DATA = 'RECEIVED_AUTH_DATA';
export const SET_CALLBACK_ON_SUCCEESS_AUTH = 'SET_CALLBACK_ON_SUCCEESS_AUTH';
export const CLEAR_CALLBACK_ON_SUCCEESS_AUTH = 'CLEAR_CALLBACK_ON_SUCCEESS_AUTH';

// User
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_SET_MY_ID = 'USER_SET_MY_ID';
export const USER_SET_PROFILE = 'USER_SET_PROFILE';
export const USER_RECEIVE_PROFILE = 'USER_RECEIVE_PROFILE';
export const USER_SET_PHOTOS_CONFIG = 'USER_SET_PHOTOS_CONFIG';
export const USER_CLOSE_PROFILE = 'USER_CLOSE_PROFILE';
export const USER_LOGOUT = 'USER_LOGOUT';

// Search
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';
export const SELECT_TAG = 'SELECT_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SEARCH_SET_PENDING = 'SEARCH_SET_PENDING';

//Conversation
export const CONVERSATION_SET = 'CONVERSATION_SET';
export const CONVERSATION_RECEIVE_MESSAGE = 'CONVERSATION_RECEIVE_MESSAGE';
export const CONVERSATION_LOAD_MESSAGE = 'CONVERSATION_LOAD_MESSAGE';
export const CONVERSATION_SET_SHOW_MENU = 'CONVERSATION_SET_SHOW_MENU';
export const CONVERSATION_SET_SHOW_STATUS_MENU = 'CONVERSATION_SET_SHOW_STATUS_MENU';
export const CONVERSATION_CONFIRM_MSG = 'CONVERSATION_CONFIRM_MSG';
export const CONVERSATION_CONFIRM_STATUS_MSG = 'CONVERSATION_CONFIRM_STATUS_MSG';
export const CONVERSATION_INC_LENGTH_LIST = 'CONVERSATION_INC_LENGTH_LIST';
export const CONVERSATION_SEND_STATUS = 'CONVERSATION_SEND_STATUS';
export const CONVERSATION_OPEN_IMG_POPUP = 'CONVERSATION_OPEN_IMG_POPUP';
export const CONVERSATION_CLOSE = 'CONVERSATION_CLOSE';

//Lead
export const LEAD_INIT = 'LEAD_INIT';
export const LEAD_RECEIVE = 'LEAD_RECEIVE';
export const LEAD_SET_TAB = 'LEAD_SET_TAB';
export const LEAD_INC_NOTIFY = 'LEAD_INC_NOTIFY';
export const LEAD_CLEAR_NOTIFY = 'LEAD_CLEAR_NOTIFY';
export const LEAD_INC_LENGTH_LIST = 'LEAD_INC_LENGTH_LIST';
export const LEAD_UPDATE = 'LEAD_UPDATE';
export const LEAD_SET_SCROLL = 'LEAD_SET_SCROLL';
export const LEAD_CLOSE = 'LEAD_CLOSE';
