// Products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_MORE_PRODUCTS = 'RECEIVE_MORE_PRODUCTS';
export const OPEN_PRODUCT = 'OPEN_PRODUCT';
export const WAIT_PRODUCTS_RESPONSE = 'WAIT_PRODUCTS_RESPONSE';
export const RECEIVE_PRODUCTS_RESPONSE = 'RECEIVE_PRODUCTS_RESPONSE';
export const ENABLE_INFINITY_PRODUCTS = 'ENABLE_INFINITY_PRODUCTS';
export const SET_COLUMN_NUMBER = 'SET_COLUMN_NUMBER';

// Conversation
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const LOAD_MESSAGE = 'LOAD_MESSAGE';
export const CLOSE_CONVERSATION = 'CLOSE_CONVERSATION';
export const INCREMENT_CHAT_NOTIFY_COUNT = 'INCREMENT_CHAT_NOTIFY_COUNT';
export const CLEAR_CHAT_NOTIFY_COUNT = 'CLEAR_CHAT_NOTIFY_COUNT';
export const UPDATE_CHAT_MEMBERS = 'UPDATE_CHAT_MEMBERS';
export const SET_SHOW_MENU = 'SET_SHOW_MENU';
export const SET_SHOW_STATUS_MENU = 'SET_SHOW_STATUS_MENU';
//export const CREATE_MESSAGE = 'CREATE_MESSAGE';

// Auth
export const RECEIVED_AUTH_DATA = 'RECEIVED_AUTH_DATA';

// User
export const RECEIVE_USER = 'RECEIVE_USER';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

// Search
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';
export const SELECT_TAG = 'SELECT_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

// Popups
export const SHOW_POPUP_SIGNUP = 'SHOW_POPUP_SIGNUP';
export const HIDE_POPUP_SIGNUP = 'HIDE_POPUP_SIGNUP';
export const SHOW_POPUP_FAST_SIGNUP = 'SHOW_POPUP_FAST_SIGNUP';
export const HIDE_POPUP_FAST_SIGNUP = 'HIDE_POPUP_FAST_SIGNUP';
